pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=netlify/stupefied-cray-130f5a/deploy-preview
    actions:
      merge:
        method: merge
